### PR TITLE
feat: add support for multiple keyboard keys

### PR DESCRIPTION
**Pull request by wevsty**
By adding the trigger_keys function, the code can support up to 6 normal keys and 8 function keys being pressed or released at the same time.

For example:
If you need to press the up and left keyboard keys at the same time, you cannot do this using press(), but you can use the newly added trigger_keys()

I have used this function in another project and it works fine.

### CODE REVIEW

**Comment by pradishb** [comment]
Hello @wevsty, the `send()` function can already do what `trigger_keys()` does. I do not think that the new function `trigger_keys()` is necessary.

**Comment by wevsty** [comment]
Hello @pradishb :
Of course ```send()``` can be used to press and release multiple keyboard keys, but ```send()``` is not easy to use.
If I didn't read the chip datasheet, I wouldn't necessarily be able to figure out how to press multiple buttons at the same time.
```press()``` ```release()``` ```write()``` None of these functions can do this, And these functions may break the keyboard state after using ```send()```.
I still think it's appropriate to press multiple keyboard keys at once to provide an interface like ```press()```.
Of course, we can also choose to write documentation or examples to show this.

**Comment by pradishb** [comment]
Your point is valid, I agree that `trigger_keys()` is a better interface than `send()`.

But before merging the PR, there are few things I would like to point out in your code.

1. If there are more than 6 keys, the code only slices 5 items.
```py
>>> press_keys = [1, 2, 3, 4, 5, 6, 7]
>>> press_keys = press_keys[0:5]
>>> press_keys
[1, 2, 3, 4, 5]
```

2. The `trigger_keys()` should raise an exception when the length of keys is more than 6, instead of ignoring the some keys. Also, note that the keys ignored will be not from the end of the `keys` list because the order is changed in the line `press_keys = list(set(press_keys))`.

3. The type of `keys` parameter is `list[Unknown]`.

4. The code exceeded the maximum line length of 79 columns.

Here is the modified version of your code.

```py
def trigger_keys(
    ser: Serial, keys: list[str], modifiers: List[Modifier] = []
) -> None:
    press_keys = keys.copy()
    press_modifiers = modifiers.copy()
    press_keys = list(set(press_keys))
    press_modifiers = list(set(press_modifiers))
    # Supports press to 6 normal buttons at the same time
    press_keys = press_keys[:6]
    if len(press_keys) > 6:
        raise TooManyKeysError(
            "CH9329 supports maximum of 6 keys to be pressed at once."
        )
    # if len(keys) <= 6, add empty keys
    while len(press_keys) != 6:
        press_keys.append("")
    send(
        ser,
        (
            press_keys[0],
            press_keys[1],
            press_keys[2],
            press_keys[3],
            press_keys[4],
            press_keys[5],
        ),
        press_modifiers,
    )
```

**Comment by wevsty** [comment]
>     1. If there are more than 6 keys, the code only slices 5 items.

This is a mistake, thanks for pointing it out.

>     2. The `trigger_keys()` should raise an exception when the length of keys is more than 6, instead of ignoring the some keys. Also, note that the keys ignored will be not from the end of the `keys` list because the order is changed in the line `press_keys = list(set(press_keys))`.

For the most case, I think it's acceptable to ignore more keys when the number of keys exceeds the number supported by the hardware, but throwing exceptions is a better option for the library, which is a good change.

In addition, the control keys only support a maximum of 8 keys to be pressed at the same time.If an exception is to be thrown, the control key should also be checked.

>     3. The type of `keys` parameter is `list[Unknown]`.
Clarify the types within the list this looks great.

>     4. The code exceeded the maximum line length of 79 columns.
I was using a formatting tool that may not be configured quite the same as yours, so I didn't format the code.

I have changed the code to ensure compliance.

**Review by pradishb — APPROVED** [review]

**Pull request merged**
